//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonTracker.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nestali
    {
        public int idNestali { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public Nullable<int> godinaRodenja { get; set; }
        public byte[] fotografija { get; set; }
        public Nullable<System.DateTime> datumNestanka { get; set; }
        public string mjestoNestanka { get; set; }
        public Nullable<int> idKorisnik { get; set; }
        public byte[] spol { get; set; }
        public string komentar { get; set; }
        public string visina { get; set; }
        public string tezina { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
    }
}
