//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonTrackerDatamodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oci
    {
        public int idOci { get; set; }
        public byte[] layer { get; set; }
    
        public virtual Skica Skica { get; set; }
    }
}
